carina/blueprints/distritos/views.py
"""
Distritos, vistas
"""

import json

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.safe_string import safe_clave, safe_message, safe_string
from carina.blueprints.bitacoras.models import Bitacora
from carina.blueprints.distritos.forms import DistritoForm
from carina.blueprints.distritos.models import Distrito
from carina.blueprints.modulos.models import Modulo
from carina.blueprints.permisos.models import Permiso
from carina.blueprints.usuarios.decorators import permission_required

MODULO = "DISTRITOS"

distritos = Blueprint("distritos", __name__, template_folder="templates")


@distritos.before_request
@login_required
@permission_required(MODULO, Permiso.VER)
def before_request():
    """Permiso por defecto"""


@distritos.route("/distritos/datatable_json", methods=["GET", "POST"])
def datatable_json():
    """DataTable JSON para listado de Distritos"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Distrito.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "clave" in request.form:
        try:
            clave = safe_clave(request.form["clave"])
            if clave != "":
                consulta = consulta.filter(Distrito.clave.contains(clave))
        except ValueError:
            pass
    if "nombre" in request.form:
        nombre = safe_string(request.form["nombre"], save_enie=True)
        if nombre != "":
            consulta = consulta.filter(Distrito.nombre.contains(nombre))
    # Ordenar y paginar
    registros = consulta.order_by(Distrito.clave).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "detalle": {
                    "clave": resultado.clave,
                    "url": url_for("distritos.detail", distrito_id=resultado.id),
                },
                "nombre": resultado.nombre,
                "nombre_corto": resultado.nombre_corto,
                "es_distrito": resultado.es_distrito,
                "es_jurisdiccional": resultado.es_jurisdiccional,
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@distritos.route("/distritos/select_json", methods=["GET", "POST"])
def select_json():
    """Select JSON para Distritos"""
    # Consultar
    consulta = Distrito.query.filter_by(estatus="A").order_by(Distrito.nombre)
    # Si viene es_archivo_solicitante como parametro en el URL como true o false
    if "es_distrito" in request.args:
        es_distrito = request.args["es_distrito"] == "true"
        consulta = consulta.filter_by(es_distrito=es_distrito)
    # Elaborar datos para Select
    data = []
    for resultado in consulta.all():
        data.append(
            {
                "id": resultado.id,
                "nombre": resultado.nombre,
            }
        )
    # Entregar JSON
    return json.dumps(data)


@distritos.route("/distritos")
def list_active():
    """Listado de Distritos activos"""
    return render_template(
        "distritos/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Distritos",
        estatus="A",
    )


@distritos.route("/distritos/inactivos")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de Distritos inactivos"""
    return render_template(
        "distritos/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Distritos inactivos",
        estatus="B",
    )


@distritos.route("/distritos/<int:distrito_id>")
def detail(distrito_id):
    """Detalle de un Distrito"""
    distrito = Distrito.query.get_or_404(distrito_id)
    return render_template("distritos/detail.jinja2", distrito=distrito)


@distritos.route("/distritos/nuevo", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.CREAR)
def new():
    """Nuevo Distrito"""
    form = DistritoForm()
    if form.validate_on_submit():
        es_valido = True
        # Validar que la clave no se repita
        clave = safe_clave(form.clave.data)
        if Distrito.query.filter_by(clave=clave).first():
            flash("La clave ya está en uso. Debe de ser única.", "warning")
            es_valido = False
        # Validar que el nombre no se repita
        nombre = safe_string(form.nombre.data, save_enie=True)
        if Distrito.query.filter_by(nombre=nombre).first():
            flash("La nombre ya está en uso. Debe de ser único.", "warning")
            es_valido = False
        # Si es válido, guardar
        if es_valido is True:
            distrito = Distrito(
                clave=clave,
                nombre=nombre,
                nombre_corto=safe_string(form.nombre_corto.data, save_enie=True),
                es_distrito_judicial=form.es_distrito_judicial.data,
                es_distrito=form.es_distrito.data,
                es_jurisdiccional=form.es_jurisdiccional.data,
            )
            distrito.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Nuevo Distrito {distrito.clave}"),
                url=url_for("distritos.detail", distrito_id=distrito.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    return render_template("distritos/new.jinja2", form=form)


@distritos.route("/distritos/edicion/<int:distrito_id>", methods=["GET", "POST"])
@permission_required(MODULO, Permiso.MODIFICAR)
def edit(distrito_id):
    """Editar Distrito"""
    distrito = Distrito.query.get_or_404(distrito_id)
    form = DistritoForm()
    if form.validate_on_submit():
        es_valido = True
        # Si cambia la clave verificar que no este en uso
        clave = safe_clave(form.clave.data)
        if distrito.clave != clave:
            distrito_existente = Distrito.query.filter_by(clave=clave).first()
            if distrito_existente and distrito_existente.id != distrito.id:
                es_valido = False
                flash("La clave ya está en uso. Debe de ser única.", "warning")
        # Si cambia el nombre verificar que no este en uso
        nombre = safe_string(form.nombre.data, save_enie=True)
        if distrito.nombre != nombre:
            distrito_existente = Distrito.query.filter_by(nombre=nombre).first()
            if distrito_existente and distrito_existente.id != distrito.id:
                es_valido = False
                flash("El nombre ya está en uso. Debe de ser único.", "warning")
        # Si es válido, actualizar
        if es_valido:
            distrito.clave = clave
            distrito.nombre = nombre
            distrito.nombre_corto = safe_string(form.nombre_corto.data, save_enie=True)
            distrito.es_distrito_judicial = form.es_distrito_judicial.data
            distrito.es_distrito = form.es_distrito.data
            distrito.es_jurisdiccional = form.es_jurisdiccional.data
            distrito.save()
            bitacora = Bitacora(
                modulo=Modulo.query.filter_by(nombre=MODULO).first(),
                usuario=current_user,
                descripcion=safe_message(f"Editado Distrito {distrito.clave}"),
                url=url_for("distritos.detail", distrito_id=distrito.id),
            )
            bitacora.save()
            flash(bitacora.descripcion, "success")
            return redirect(bitacora.url)
    form.clave.data = distrito.clave
    form.nombre.data = distrito.nombre
    form.nombre_corto.data = distrito.nombre_corto
    form.es_distrito_judicial.data = distrito.es_distrito_judicial
    form.es_distrito.data = distrito.es_distrito
    form.es_jurisdiccional.data = distrito.es_jurisdiccional
    return render_template("distritos/edit.jinja2", form=form, distrito=distrito)


@distritos.route("/distritos/eliminar/<int:distrito_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def delete(distrito_id):
    """Eliminar Distrito"""
    distrito = Distrito.query.get_or_404(distrito_id)
    if distrito.estatus == "A":
        distrito.delete()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Eliminado Distrito {distrito.clave}"),
            url=url_for("distritos.detail", distrito_id=distrito.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("distritos.detail", distrito_id=distrito.id))


@distritos.route("/distritos/recuperar/<int:distrito_id>")
@permission_required(MODULO, Permiso.ADMINISTRAR)
def recover(distrito_id):
    """Recuperar Distrito"""
    distrito = Distrito.query.get_or_404(distrito_id)
    if distrito.estatus == "B":
        distrito.recover()
        bitacora = Bitacora(
            modulo=Modulo.query.filter_by(nombre=MODULO).first(),
            usuario=current_user,
            descripcion=safe_message(f"Recuperado Distrito {distrito.clave}"),
            url=url_for("distritos.detail", distrito_id=distrito.id),
        )
        bitacora.save()
        flash(bitacora.descripcion, "success")
    return redirect(url_for("distritos.detail", distrito_id=distrito.id))

carina/blueprints/distritos/templates/distritos/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Distrito {{ distrito.nombre_corto }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Distrito ' + distrito.nombre_corto) %}
        {{ topbar.button_previous('Distritos', url_for('distritos.list_active')) }}
        {% if current_user.can_edit('DISTRITOS') %}
            {{ topbar.button_edit('Editar', url_for('distritos.edit', distrito_id=distrito.id)) }}
        {% endif %}
        {% if current_user.can_admin('DISTRITOS') %}
            {% if distrito.estatus == 'A' %}{{ topbar.button_delete('Eliminar', url_for('distritos.delete', distrito_id=distrito.id)) }}{% endif %}
            {% if distrito.estatus == 'B' %}{{ topbar.button_recover('Recuperar', url_for('distritos.recover', distrito_id=distrito.id)) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call detail.card(estatus=distrito.estatus) %}
        {{ detail.label_value_big('Clave', distrito.clave) }}
        {{ detail.label_value('Nombre', distrito.nombre) }}
        {{ detail.label_value('Nombre corto', distrito.nombre_corto) }}
        {{ detail.label_value_boolean('Es Distrito Judicial (pjecz.gob.mx)', distrito.es_distrito_judicial) }}
        {{ detail.label_value_boolean('Es Distrito (geográfico)', distrito.es_distrito) }}
        {{ detail.label_value_boolean('Es Jurisdiccional', distrito.es_jurisdiccional) }}
        {# detail.label_value('Creado', moment(distrito.creado).format('llll')) #}
    {% endcall %}
    {% if current_user.can_view('AUTORIDADES') %}
        {% call detail.card('Autoridades') %}
            <!-- Filtros autoridades -->
            <div class="row">
                <div class="col">
                    <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosAutoridades.buscar(); return false;">
                        <div class="col-2">
                            <div class="form-floating">
                                <input id="filtroClave" type="text" class="form-control" aria-label="Clave" style="text-transform: uppercase;">
                                <label for="filtroClave">Clave</label>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-floating">
                                <input id="filtroDescripcion" type="text" class="form-control" aria-label="Descripcion" style="text-transform: uppercase;">
                                <label for="filtroDescripcion">Descripción</label>
                            </div>
                        </div>
                        <div class="col-6 text-end">
                            <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosAutoridades.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                            <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosAutoridades.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- DataTable autoridades -->
            <table id="autoridades_datatable" class="table display nowrap" style="width:100%">
                <thead>
                    <tr>
                        <th>Clave</th>
                        <th>Descripción corta</th>
                        <th>Municipio</th>
                        <th>Extinto</th>
                    </tr>
                </thead>
            </table>
        {% endcall %}
    {% endif %}
{% endblock %}

{% block custom_javascript %}
    {% if current_user.can_admin('DISTRITOS') %}
        {% if distrito.estatus == 'A' %}{{ modals.custom_javascript_delete('Eliminar', '¿Eliminar a ' + distrito.nombre + '?') }}{% endif %}
        {% if distrito.estatus == 'B' %}{{ modals.custom_javascript_recover('Recuperar', '¿Recuperar a ' + distrito.nombre + '?') }}{% endif %}
    {% endif %}
    {{ detail.moment_js(moment) }}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    {% if current_user.can_view('AUTORIDADES') %}
        <script>
            // DataTable autoridades
            const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
            let configDataTable = constructorDataTable.config();
            configDataTable['ajax']['url'] = '/autoridades/datatable_json';
            configDataTable['ajax']['data'] = { 'estatus': "A", 'distrito_id': {{ distrito.id}} };
            configDataTable['columns'] = [
                { data: "detalle" },
                { data: "descripcion_corta" },
                { data: "municipio" },
                { data: "es_extinto" }
            ];
            configDataTable['columnDefs'] = [
                {
                    targets: 0, // detalle
                    data: null,
                    render: function(data, type, row, meta) {
                        return '<a href="' + data.url + '">' + data.clave + '</a>';
                    }
                },
                {
                    targets: 2, // municipio
                    data: null,
                    render: function(data, type, row, meta) {
                        if (data.nombre.length > 32) {
                            nombre = data.nombre.substr(0, 32) + '…';
                        } else {
                            nombre = data.nombre;
                        }
                        if (data.url != '') {
                            return '<a href="' + data.url + '">' + nombre + '</a>';
                        }
                        return nombre;
                    }
                }
            ];
            // Filtros autoridades
            const filtrosAutoridades = new FiltrosDataTable('#autoridades_datatable', configDataTable);
            filtrosAutoridades.agregarInput('filtroClave', 'clave');
            filtrosAutoridades.agregarInput('filtroDescripcion', 'descripcion');
            filtrosAutoridades.precargar();
        </script>
    {% endif %}
{% endblock %}

carina/blueprints/distritos/templates/distritos/edit.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Editar Distrito {{ distrito.clave }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Editar Distrito ' + distrito.clave) %}
        {{ topbar.button_cancel() }}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% set form_kwargs = {'distrito_id': distrito.id} %}
        {% call f.form_tag('distritos.edit', fid='distrito_form', **form_kwargs) %}
            {% call f.form_group(form.clave) %}{% endcall %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.nombre_corto) %}{% endcall %}
            {% call f.form_group(form.es_distrito_judicial) %}{% endcall %}
            {% call f.form_group(form.es_distrito) %}{% endcall %}
            {% call f.form_group(form.es_jurisdiccional) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}

carina/blueprints/distritos/templates/distritos/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}{{ titulo }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_view('AUTORIDADES') %}
            {{ topbar.button('Autoridades', url_for('autoridades.list_active'), 'mdi:scale-balance') }}
        {% endif %}
        {% if current_user.can_admin('DISTRITOS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('distritos.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('distritos.list_active')) }}{% endif %}
        {% endif %}
        {% if current_user.can_insert('DISTRITOS') %}
            {{ topbar.button_new('Nuevo Distrito', url_for('distritos.new')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <!-- Filtros distritos -->
        <div class="row">
            <div class="col">
                <form class="row g-1 mb-3" id="filtradorForm" onsubmit="filtrosDistritos.buscar(); return false;">
                    <div class="col-2">
                        <div class="form-floating">
                            <input id="filtroDistritoClave" type="text" class="form-control" aria-label="Clave" style="text-transform: uppercase;">
                            <label for="filtroDistritoClave">Clave</label>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-floating">
                            <input id="filtroDistritoNombre" type="text" class="form-control" aria-label="Nombre" style="text-transform: uppercase;">
                            <label for="filtroDistritoNombre">Nombre</label>
                        </div>
                    </div>
                    <div class="col-6 text-end">
                        <button title="Buscar" class="btn btn-primary btn-lg" onclick="filtrosDistritos.buscar(); return false;" id="button-buscar"><span class="iconify" data-icon="mdi:magnify"></span></button>
                        <button title="Limpiar" class="btn btn-warning btn-lg" type="reset" onclick="filtrosDistritos.limpiar();" id="button-limpiar"><span class="iconify" data-icon="mdi:broom"></span></button>
                    </div>
                </form>
            </div>
        </div>
        <!-- DataTable distritos -->
        <table id="distritos_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th>Nombre corto</th>
                    <th>Es D.</th>
                    <th>Es J.</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    <script src="/static/js/datatables-constructor.js"></script>
    <script src="/static/js/datatables-filtros.js"></script>
    <script>
        // DataTable distritos
        const constructorDataTable = new ConfigDataTable( '{{ csrf_token() }}' );
        let configDataTable = constructorDataTable.config();
        configDataTable['ajax']['url'] = '/distritos/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: 'detalle' },
            { data: 'nombre' },
            { data: 'nombre_corto' },
            { data: 'es_distrito' },
            { data: 'es_jurisdiccional' }
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.clave + '</a>';
                }
            },
            {
                targets: [3, 4], // es_distrito, es_jurisdiccional
                data: null,
                render: function(data, type, row, meta) {
                    if (data) { return 'Si'; } else { return ''; }
                }
            }
        ];
        // Filtros autoridades
        const filtrosDistritos = new FiltrosDataTable('#distritos_datatable', configDataTable);
        filtrosDistritos.agregarInput('filtroDistritoClave', 'clave');
        filtrosDistritos.agregarInput('filtroDistritoNombre', 'nombre');
        filtrosDistritos.precargar();
    </script>
{% endblock %}

carina/blueprints/distritos/templates/distritos/new.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/form.jinja2' as f with context %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Nuevo Distrito{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons('Nuevo Distrito') %}
        {{ topbar.button_cancel() }}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call f.card() %}
        {% call f.form_tag('distritos.new', fid='distrito_form') %}
            {% call f.form_group(form.clave) %}{% endcall %}
            {% call f.form_group(form.nombre) %}{% endcall %}
            {% call f.form_group(form.nombre_corto) %}{% endcall %}
            {% call f.form_group(form.es_distrito_judicial) %}{% endcall %}
            {% call f.form_group(form.es_distrito) %}{% endcall %}
            {% call f.form_group(form.es_jurisdiccional) %}{% endcall %}
            {% call f.form_group(form.guardar) %}{% endcall %}
        {% endcall %}
    {% endcall %}
{% endblock %}