carina/blueprints/tareas/models.py
"""
Tareas, modelos
"""

import redis
import rq
from flask import current_app
from sqlalchemy import ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from carina.extensions import database
from lib.universal_mixin import UniversalMixin


class Tarea(database.Model, UniversalMixin):
    """Tarea"""

    # Nombre de la tabla
    __tablename__ = "tareas"

    # Clave primaria NOTA: El id es string y es el mismo que usa el RQ worker
    id: Mapped[str] = mapped_column(String(36), primary_key=True)

    # Clave foránea
    usuario_id: Mapped[int] = mapped_column(ForeignKey("usuarios.id"))
    usuario: Mapped["Usuario"] = relationship("Usuario", back_populates="tareas")

    # Columnas
    archivo: Mapped[str] = mapped_column(String(256), default="", server_default="")
    comando: Mapped[str] = mapped_column(String(256), index=True)
    ha_terminado: Mapped[bool] = mapped_column(default=False)
    mensaje: Mapped[str] = mapped_column(String(1024), default="", server_default="")
    url: Mapped[str] = mapped_column(String(512), default="", server_default="")

    def get_rq_job(self):
        """Helper method that loads the RQ Job instance"""
        try:
            rq_job = rq.job.Job.fetch(self.id, connection=current_app.redis)
        except (redis.exceptions.RedisError, rq.exceptions.NoSuchJobError):
            return None
        return rq_job

    def get_progress(self):
        """Returns the progress percentage for the task"""
        job = self.get_rq_job()
        return job.meta.get("progress", 0) if job is not None else 100

    def __repr__(self):
        """Representación"""
        return f"<Tarea {self.id}>"

carina/blueprints/tareas/views.py
"""
Tareas, vistas
"""

import json

from flask import Blueprint, current_app, flash, make_response, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from lib.datatables import get_datatable_parameters, output_datatable_json
from lib.exceptions import MyAnyError
from lib.google_cloud_storage import get_blob_name_from_url, get_file_from_gcs
from carina.blueprints.permisos.models import Permiso
from carina.blueprints.tareas.models import Tarea
from carina.blueprints.usuarios.decorators import permission_required

MODULO = "TAREAS"

tareas = Blueprint("tareas", __name__, template_folder="templates")


# @tareas.before_request
# @login_required
# @permission_required(MODULO, Permiso.VER)
# def before_request():
#     """Permiso por defecto"""


@tareas.route("/tareas/datatable_json", methods=["GET", "POST"])
@login_required
@permission_required(MODULO, Permiso.VER)
def datatable_json():
    """DataTable JSON para listado de Tareas"""
    # Tomar parámetros de Datatables
    draw, start, rows_per_page = get_datatable_parameters()
    # Consultar
    consulta = Tarea.query
    # Primero filtrar por columnas propias
    if "estatus" in request.form:
        consulta = consulta.filter_by(estatus=request.form["estatus"])
    else:
        consulta = consulta.filter_by(estatus="A")
    if "comando" in request.form:
        consulta = consulta.filter_by(comando=request.form["comando"])
    if "usuario_id" in request.form:
        consulta = consulta.filter_by(usuario_id=request.form["usuario_id"])
    # Ordenar y paginar
    registros = consulta.order_by(Tarea.creado.desc()).offset(start).limit(rows_per_page).all()
    total = consulta.count()
    # Elaborar datos para DataTable
    data = []
    for resultado in registros:
        data.append(
            {
                "creado": resultado.creado.strftime("%Y-%m-%d %H:%M:%S"),
                "detalle": {
                    "comando": resultado.comando,
                    "url": url_for("tareas.detail", tarea_id=resultado.id),
                },
                "ha_terminado": resultado.ha_terminado,
                "mensaje": resultado.mensaje,
                "usuario": {
                    "email": resultado.usuario.email,
                    "url": (
                        url_for("usuarios.detail", usuario_id=resultado.usuario_id) if current_user.can_view("USUARIOS") else ""
                    ),
                },
            }
        )
    # Entregar JSON
    return output_datatable_json(draw, total, data)


@tareas.route("/tareas")
@login_required
@permission_required(MODULO, Permiso.VER)
def list_active():
    """Listado de Tareas activos"""
    return render_template(
        "tareas/list.jinja2",
        filtros=json.dumps({"estatus": "A"}),
        titulo="Tareas",
        estatus="A",
    )


@tareas.route("/tareas/inactivos")
@login_required
@permission_required(MODULO, Permiso.ADMINISTRAR)
def list_inactive():
    """Listado de Tareas inactivos"""
    return render_template(
        "tareas/list.jinja2",
        filtros=json.dumps({"estatus": "B"}),
        titulo="Tareas inactivos",
        estatus="B",
    )


@tareas.route("/tareas/<tarea_id>")
@login_required
def detail(tarea_id):
    """Detalle de un Tarea"""
    tarea = Tarea.query.get_or_404(tarea_id)
    return render_template("tareas/detail.jinja2", tarea=tarea)


@tareas.route("/tareas/<tarea_id>/xlsx")
@login_required
def download_xlsx(tarea_id):
    """Descargar archivo XLSX de una Tarea"""

    # Consultar la Tarea
    tarea = Tarea.query.get_or_404(tarea_id)

    # Si no tiene URL, regidir a la página de detalle
    if tarea.url == "":
        flash("Esta tarea no tiene un URL para descargar", "warning")
        return redirect(url_for("tareas.detail", tarea_id=tarea.id))

    # Si no tiene nombre para el archivo, regidir a la página de detalle
    descarga_nombre = tarea.archivo
    if descarga_nombre == "":
        flash("Esta tarea no tiene un archivo para descargar", "warning")
        return redirect(url_for("tareas.detail", tarea_id=tarea.id))

    # Validar que descarga_nombre termine en .xlsx
    if not descarga_nombre.endswith(".xlsx"):
        flash("Esta tarea no tiene un archivo XLSX para descargar", "warning")
        return redirect(url_for("tareas.detail", tarea_id=tarea.id))

    # Obtener el contenido del archivo desde Google Storage
    try:
        descarga_contenido = get_file_from_gcs(
            bucket_name=current_app.config["CLOUD_STORAGE_DEPOSITO"],
            blob_name=get_blob_name_from_url(tarea.url),
        )
    except MyAnyError as error:
        flash(str(error), "danger")
        return redirect(url_for("tareas.detail", tarea_id=tarea.id))

    # Descargar un archivo XLSX
    response = make_response(descarga_contenido)
    response.headers["Content-Type"] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    response.headers["Content-Disposition"] = f"attachment; filename={descarga_nombre}"
    return response

carina/blueprints/tareas/templates/tareas/detail.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/detail.jinja2' as detail %}
{% import 'macros/modals.jinja2' as modals %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}Tarea {{ tarea.id | string }}{% endblock %}

{% block topbar_actions %}
    {% if tarea.ha_terminado %}
        {% set cabecera = 'Tarea terminada' %}
    {% else %}
        {% set cabecera = 'Tarea en ejecución' %}
    {% endif %}
    {% call topbar.page_buttons(cabecera) %}
        {% if current_user.can_view('TAREAS') %}
            {{ topbar.button_previous('Tareas', url_for('tareas.list_active')) }}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% if tarea.ha_terminado %}
        {% set border_class = 'border-success' %}
    {% else %}
        {% set border_class = 'border-info' %}
    {% endif %}
    {% call detail.card(estatus=tarea.estatus) %}
        {{ detail.label_value('Usuario', tarea.usuario.nombre) }}
        {{ detail.label_value('Comando', tarea.comando) }}
        {{ detail.label_value('Mensaje', tarea.mensaje) }}
        {% if tarea.url %}
            <a type="button" class="w-100 btn btn-lg btn-success my-2" href="{{ url_for('tareas.download_xlsx', tarea_id=tarea.id) }}" target="_blank">
                <span class="iconify" data-icon="mdi:file-download" style="font-size: 2.0em; margin-right: 4px;"></span>
                {{ tarea.archivo }}
            </a>
        {% endif %}
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ detail.moment_js(moment) }}
{% endblock %}

carina/blueprints/tareas/templates/tareas/list.jinja2
{% extends 'layouts/app.jinja2' %}
{% import 'macros/list.jinja2' as list %}
{% import 'macros/topbar.jinja2' as topbar %}

{% block title %}{{ titulo }}{% endblock %}

{% block topbar_actions %}
    {% call topbar.page_buttons(titulo) %}
        {% if current_user.can_admin('TAREAS') %}
            {% if estatus == 'A' %}{{ topbar.button_list_inactive('Inactivos', url_for('tareas.list_inactive')) }}{% endif %}
            {% if estatus == 'B' %}{{ topbar.button_list_active('Activos', url_for('tareas.list_active')) }}{% endif %}
        {% endif %}
    {% endcall %}
{% endblock %}

{% block content %}
    {% call list.card() %}
        <table id="tareas_datatable" class="table {% if estatus == 'B'%}table-dark{% endif %} display nowrap" style="width:100%">
            <thead>
                <tr>
                    <th>Comando</th>
                    <th>Ha terminado</th>
                    <th>Mensaje</th>
                    <th>Usuario</th>
                    <th>Creado</th>
                </tr>
            </thead>
        </table>
    {% endcall %}
{% endblock %}

{% block custom_javascript %}
    {{ list.config_datatable() }}
    <script>
        configDataTable['ajax']['url'] = '/tareas/datatable_json';
        configDataTable['ajax']['data'] = {{ filtros }};
        configDataTable['columns'] = [
            { data: 'detalle' },
            { data: 'ha_terminado' },
            { data: 'mensaje' },
            { data: 'usuario' },
            { data: 'creado' },
        ];
        configDataTable['columnDefs'] = [
            {
                targets: 0, // detalle
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.comando + '</a>';
                }
            },
            {
                targets: 1, // ha_terminado
                data: null,
                render: function(data, type, row, meta) {
                    if (data) { return 'Terminado'; } else { return ''; }
                }
            },
            {
                targets: 2, // mensaje
                data: null,
                render: function(data, type, row, meta) {
                    return (data.length > 48 ? '<span title="'+ data +'">' + data.substr(0, 48) + '…</span>' : data);
                }
            },
            {
                targets: 3, // usuario
                data: null,
                render: function(data, type, row, meta) {
                    return '<a href="' + data.url + '">' + data.email + '</a>';
                }
            },
            {
                targets: 4, // creado
                type: "date",
                render: function (data, type, row) {
                    return moment.utc(data).local().format("YYYY-MM-DD HH:mm:ss");
                }
            }
        ];
        $('#tareas_datatable').DataTable(configDataTable);
    </script>
{% endblock %}